"""Reusable constants for intent detection and ranking."""

MOOD_TO_GENRE: dict[str, str] = {
    "motivat": "drama",
    "inspir": "drama",
    "stress": "comedy",
    "tired": "comedy",
    "relax": "comedy",
    "fun": "comedy",
    "funny": "comedy",
    "happy": "comedy",
    "feel good": "comedy",
    "sad": "comedy",
    "excited": "action",
    "scared": "horror",
    "romantic": "romance",
    "heavy": "comedy",
    "better": "comedy",
    "cheer": "comedy",
    "uplift": "comedy",
    "exhaust": "comedy",
    "depress": "comedy",
    "anxi": "comedy",
}

LITE_MOOD_KEYWORDS = {
    "lite",
    "light",
    "stress",
    "stressed",
    "tired",
    "relax",
    "fun",
    "happy",
    "feel good",
    "chill",
    "lighthearted",
    "heavy",
    "better",
    "refresh",
    "calm",
    "anxi",
    "depress",
    "exhaust",
    "uplift",
}

LITE_GENRES = {"comedy", "family", "romance", "animation"}
LATEST_KEYWORDS = {"latest", "new", "recent", "newest", "2022", "2023", "2024", "2025"}

FOLLOWUP_HINTS = {
    "first",
    "second",
    "third",
    "fourth",
    "fifth",
    "that movie",
    "this movie",
    "those movies",
    "these movies",
    "this film",
    "that film",
    "tell me more",
    "more about",
    "what about",
    "elaborate",
    "details",
    "explain",
    "describe",
    "movie 1",
    "movie 2",
    "movie 3",
    "number",
    "plot",
    "story",
    "who directed",
    "who acted",
    "stars in",
    "rating",
    "overview",
    "which one",
    "the one",
    "is it good",
    "worth watching",
    "how is it",
    "about it",
    "see it",
    "watch it",
    "who is the",
    "hero",
    "villain",
    "actor",
    "actress",
    "cast",
    "director",
    "from the list",
    "from this list",
    "from that list",
    "from your list",
    "from the above",
    "from above",
    "from these",
    "among these",
    "among them",
    "from your recommendations",
}

